// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.24.0";

// src/lib/mcp/tools/list-appointments.ts
import { createClient } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_appointments_default = defineTool({
  name: "list_appointments",
  title: "List appointments",
  description: "List property viewing appointments booked in SouthStar Realty.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("appointments").select("id, name, email, phone, municipality, property_id, preferred_date, preferred_time, message, status, created_at").order("created_at", { ascending: false }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { appointments: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/book-appointment.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z } from "npm:zod@^4.4.3";
var book_appointment_default = defineTool2({
  name: "book_appointment",
  title: "Book a property viewing",
  description: "Book a property viewing appointment with SouthStar Realty.",
  inputSchema: {
    name: z.string().trim().min(1),
    email: z.string().trim().email(),
    phone: z.string().trim().optional(),
    municipality: z.string().trim().optional(),
    property_id: z.string().trim().optional(),
    preferred_date: z.string().describe("ISO date, YYYY-MM-DD"),
    preferred_time: z.string().describe("e.g. 10:00 AM"),
    message: z.string().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("appointments").insert(input).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Appointment booked. Confirmation ID: ${data.id}` }],
      structuredContent: { appointment: data }
    };
  }
});

// src/lib/mcp/tools/list-contact-messages.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.24.0";
var list_contact_messages_default = defineTool3({
  name: "list_contact_messages",
  title: "List contact messages",
  description: "List contact form submissions sent to SouthStar Realty.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("contact_messages").select("*").order("created_at", { ascending: false }).limit(100);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { messages: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/send-contact-message.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z2 } from "npm:zod@^4.4.3";
var send_contact_message_default = defineTool4({
  name: "send_contact_message",
  title: "Send a contact message",
  description: "Send a message to SouthStar Realty via the contact form.",
  inputSchema: {
    name: z2.string().trim().min(1),
    email: z2.string().trim().email(),
    phone: z2.string().trim().optional(),
    message: z2.string().trim().min(1)
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("contact_messages").insert(input).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Message sent. ID: ${data.id}` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/tools/list-reviews.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z3 } from "npm:zod@^4.4.3";
var list_reviews_default = defineTool5({
  name: "list_reviews",
  title: "List reviews",
  description: "List client reviews for SouthStar Realty. Filter by status if provided.",
  inputSchema: {
    status: z3.enum(["pending", "approved", "rejected"]).optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("reviews").select("*").order("created_at", { ascending: false }).limit(100);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { reviews: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-review.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.91.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.24.0";
import { z as z4 } from "npm:zod@^4.4.3";
var rating = z4.number().int().min(1).max(5);
var submit_review_default = defineTool6({
  name: "submit_review",
  title: "Submit a review",
  description: "Submit a client review for SouthStar Realty. Review starts as pending until approved.",
  inputSchema: {
    name: z4.string().trim().min(1),
    feedback: z4.string().trim().min(1),
    rating_overall: rating.optional(),
    rating_service: rating.optional(),
    rating_hospitality: rating.optional(),
    rating_affordability: rating.optional(),
    rating_trust: rating.optional(),
    avatar_url: z4.string().url().optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = createClient6(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("reviews").insert(input).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Review submitted (pending). ID: ${data.id}` }],
      structuredContent: { review: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "zszlxyplymoecojebzuq";
var mcp_default = defineMcp({
  name: "southstar-realty-mcp",
  title: "SouthStar Realty MCP",
  version: "0.1.0",
  instructions: "Tools for SouthStar Realty (Oriental Mindoro real estate): book/list property viewing appointments, send/list contact messages, and submit/list client reviews. Callers act as the signed-in app user.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    list_appointments_default,
    book_appointment_default,
    list_contact_messages_default,
    send_contact_message_default,
    list_reviews_default,
    submit_review_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.24.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
